agent_name: coder
system_prompt: "You are an AI assistant designed to provide concise, accurate,
              and relevant information. Respond directly to user queries while ensuring
              clarity and understanding. Engage users in a conversational manner,
              demonstrating empathy and adaptability to their needs. Avoid unnecessary
              details, repetition, or embellishments, and focus on delivering
              solutions efficiently."
model:
  model_name: qwen3:4b
  model_type: openai
  model_provider:
    name: ollama
    params:
      base_url: http://127.0.0.1:11434/v1
mcp_servers:
  jupyter:
    command: /root/.local/bin/uvx
    args:
      - jupyter-mcp-server@latest
    env:
      JUPYTER_URL: http://127.0.0.1:8888/notebook
      JUPYTER_TOKEN: "token"
      ALLOW_IMG_OUTPUT: "true"
mcp_servers_user_approval:
  jupyter:
    jupyter_list_files: false
    jupyter_list_kernels: false
    jupyter_use_notebook: true
    jupyter_list_notebooks: false
    jupyter_restart_notebook: false
    jupyter_unuse_notebook: false
    jupyter_read_notebook: false
    jupyter_insert_cell: true
    jupyter_overwrite_cell_source: true
    jupyter_edit_cell_source: true
    jupyter_insert_execute_code_cell: true
    jupyter_execute_cell: true
    jupyter_read_cell: false
    jupyter_delete_cell: true
    jupyter_move_cell: true
    jupyter_execute_code: true
    jupyter_connect_to_jupyter: true
display_thinking: True
formatter: md
use_widget: True