[project]
name = "fine-tuning"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=2.19.1",
    "ipywidgets>=8.1.8",
    "ollama>=0.6.1",
    "peft>=0.19.1",
    "torch>=2.11.0",
    "transformers<=4.53",
    "trl>=0.11.4",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu126"
